#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace GSWAR_NewMesh_Skeleton_AnimBlueprint { class UGSWAR_NewMesh_Skeleton_AnimBlueprint_C; }

namespace GSWAR_NewMesh_Skeleton_AnimBlueprint_0 { class UGSWAR_NewMesh_Skeleton_AnimBlueprint_C; }

