// ======================================================
//  SERVER CONFIG PAGE (PLACEHOLDER)
// ======================================================
import { VerticalBox } from "std-widgets.slint";

export component ServerConfigPage {
    VerticalBox {
        alignment: center;
        Text {
            text: "Server Config (Coming Soon)";
            horizontal-alignment: center;
        }
    }
}